version: 1.0.{build}
image:
  - Visual Studio 2017
platform:
  - x64
environment:
  NODE_OPTIONS: --max-old-space-size=7168
branches:
  only:
  - master
cache:
  - node_modules
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - echo "* Running Install..."
  - ps: Install-Product node 12 x64
  - npm install npm -g
  - npm install typescript
  - npm install
  - npm -v
  - npm bin
  - npm ls --depth=0
build_script:
  - echo "* Running Build..."
  - node_modules\\typescript\\bin\\tsc -p tsconfig.serve.json && ng build -- -c production && electron-builder build --windows
artifacts:
  - path: 'release\*.*'
test: off
