version: 1.0.{build}
image:
  - Visual Studio 2019
platform:
  - x64
branches:
  only:
  - master
cache:
  - node_modules
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node Current x64
  - npm install npm -g
  - npm install
build_script:
- sh: >-
    export NODE_OPTIONS="--max-old-space-size=7168" #increase to 7gb
    npm run electron:windows
artifacts:
- path: release/*.exe